# Generated by Django 5.0.7 on 2024-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newusers",
            name="password",
            field=models.CharField(max_length=8),
        ),
    ]
