# Generated by Django 5.0.7 on 2024-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_newusers_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExistingUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
