# Generated by Django 5.0.7 on 2024-08-04 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_existingusers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExistingUsers",
            new_name="ExistingUser",
        ),
        migrations.RenameModel(
            old_name="NewUsers",
            new_name="NewUser",
        ),
    ]
