# Generated by Django 5.0.7 on 2024-08-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_message_room"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExistingUser",
        ),
        migrations.AlterField(
            model_name="newuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
